### ISSUE TITLE
💚 GitHub Actions で CI/CD を導入する

### ISSUE THREAD

**Issue by tora-muscle** [k-saito-en/1weekPDCA#14]
## 🎫 関連課題
子課題
- #13 

## ✨ 実現したいこと

▼ when?
- #2 、`developブランチ`にマージ後

▼ what?・why?
以下の自動化
- [x] `コードのビルド`
  Xcodeがインストールされている仮想マシンを使用して、リポジトリのコードを自動的にビルドすることができる。開発者は`Xcodeを起動する ▶︎ プロジェクトを開く ▶︎ ターゲットを選択する ▶︎ ビルド設定を構成する ▶︎ ビルドを実行する ▶︎ エラーを修正する ▶︎ もう一度ビルドを実行する`といった作業を踏む手間がなくなり、生産性が向上する。

- [x] `テストの実行`
   コードの品質を保証するために、コードに対するユニットテストを自動的に実行することができる。また、UIテストも実行することができる。これらのテストは、GitHub Actionsが自動的に実行するため、開発者は手動でテストする必要がなくなる。

- [x] `静的解析`
   コードの品質を向上し、バグの検出と修正を容易にすることができる。

---

↓２次開発以降`ReOpen`対応↓

- [ ] `アプリの署名と配布`
   アプリを自動的に署名し、App Store Connectにアップロードすることができる。これにより、アプリのリリースプロセスが自動化され、開発者は手動でアプリを署名して配布する必要がなくなる。バージョンタグ付けなどもできるらしい！
   

## 🚩 やらないこと
- `通知の自動化`
  アプリのビルド、テスト、静的解析、署名、配布などの各ステップの完了時に、Slack、Microsoft Teamsなどのツールを介して通知を送信することができる。これにより、開発者はすぐに問題に対処し、アプリをリリースするための準備をすることができる。
  が。。。個人開発なので割愛。。

## 🔀 達成条件
- `一次開発`
  `コードのビルド`~`静的解析`までを自動化し、ユニット実装毎にテストコードを書く癖をつける

- `二次開発以降`
   GitHub Actions を使って自動デプロイ、リリースし、保守作業をいい意味でサボれるようにする

## 👀 備考

▼ 参考記事
- https://lab.mo-t.com/blog/how-to-use-github-actions-for-ios-app

**Comment by tora-muscle** [comment]
### 🗒 CI が通らない原因の考察

▼ 原因
- `swift init`をしておらず、`Package.swift`が存在しないために、テストフェーズでの依存関係の解決ができていないように思われる。
- `.yml`自体は以下で良さそう

```yml

# このワークフローはGitHubによって認定されていないアクションを使用します。
# それらはサードパーティによって提供され、
# 別個の利用規約、プライバシーポリシー、
# ドキュメントを参照してください。

# GitHub では、コミット SHA にアクションをピン留めすることが推奨されます。
# 新しいバージョンを取得するには、SHA を更新する必要があります。
# タグまたはブランチを参照することもできますが、アクションは警告なしに変更される可能性があります。

name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.2", "5.3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```

▼ 参考文献
- https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-swift

日付跨いじゃったから明日やろー。。。

**Comment by k-saito-en** [comment]
### 🗒
Xcodeのビルドスクリプトに出力が指定されていないために毎回ビルド時に実行される警告を解決するには、スクリプトフェーズに出力の依存関係を追加する必要があります1。出力の依存関係とは、スクリプトが生成するファイルやディレクトリのことです1。出力の依存関係を指定することで、Xcodeはスクリプトが実行される必要があるかどうかを判断できます1。
ワークフローを書き換えるには、以下の手順を参考にしてください12。
Xcodeでプロジェクトを開き、ターゲットを選択します。
Build Phasesタブをクリックし、Run Scriptフェーズを探します。
Run ScriptフェーズのOutput Filesセクションに、スクリプトが生成するファイルやディレクトリのパスを追加します。パスは絶対パスまたは環境変数で指定します。
ワークフローのRun XCTestステップの前に、Output Filesセクションに追加したファイルやディレクトリをキャッシュするためのステップを追加します。actions/cache@v2アクションを使ってキャッシュできます。
詳しい説明は、参考サイト12 をご覧ください。
受信したメッセージ. Xcodeのビルドスクリプトに出力が指定されていないために毎回ビルド時に実行される警告を解決するには、スクリプトフェーズに出力の依存関係を追加する必要があります。出力の依存関係とは、スクリプトが生成するファイルやディレクトリのことです。出力の依存関係を指定することで、Xcodeはスクリプトが実行される必要があるかどうかを判断できます。 ワークフローを書き換えるには、以下の手順を参考にしてください 。 - Xcodeでプロジェクトを開き、ターゲットを選択します。 - Build Phasesタブをクリックし、Run Scriptフェーズを探します。 - Run ScriptフェーズのOutput Filesセクションに、スクリプトが生成するファイルやディレクトリのパスを追加します。パスは絶対パスまたは環境変数で指定します。 - ワークフローのRun XCTestステップの前に、Output Filesセクションに追加したファイルやディレクトリをキャッシュするためのステップを追加します。actions/cache@v2アクションを使ってキャッシュできます。 詳しい説明は、参考サイト をご覧ください。

**Comment by tora-muscle** [comment]
### 👏 CI テスト実行成功 !!

![スクリーンショット 2023-02-25 20 25 13](https://user-images.githubusercontent.com/111550856/221354744-fe86c087-19d7-41e4-bb2c-5dbeeb79a66a.png)

**▼ ❌ テストが通らなかった原因**
- `.xcodeproj に対してテストを実行しようとしていたから`
   .xcodeproj に対してテストを実行しようとすると「 Package.swift が無い」と怒られる。これは、 Cocoapods を使ってパッケージ管理をしているのに、 Swift Package Manager を使っている際のテスト方法を指定しているから。

- `.xcworkspace 向けにテストしているのに、Cocoapods を仮想環境にインストールしなかったから`
   pod install しないと .xcworcspace ファイルは出力されない。なので「 .xcworkspace なんてファイルないよ」と怒られていた。Github Actions を実行する仮想環境に対しても、ローカルと同じ「環境構築」をしてあげる必要があった。

**▼ 🔎 解決法**

- `gem install cocoapods 、 pod install で仮想環境に .xcworcspace を作成させる`
   前述の通り、ローカルの環境構築で行った手順をワークフロー上でも再現していく。仮想環境上で作成された .xcworkspace に対して xcodebuild をかけていく

- `ダウンロードした gem 、 Podライブラリをキャッシュする`
   毎回新しい仮想環境に pod install していると時間がかかって仕方がないので、初回ダウンロード分、更新・追加分をキャッシュするように設定

<details>
<summary>👇 クリックして開く 1weekPDCA_CI.yml</summary>

```yml
 # ワークフローの名前を定義
name: 1weekPDCA_CI

# トリガーを定義
on:

  # pull request が開かれた時
  pull_request:
    types:
      - opened
      - synchronize
      
  # main, develop, featureで始まるブランチ, いずれかに push された時
  push:
    branches:
      - main
      - develop
      - feature/**
      
# キャッシュの設定
env:
  CACHE_NAME: cache-pod
  
# 実行内容を定義
jobs:

  # job にはそれぞれに名前がつけられる
  RunTestonIphone:
  
    # ランナーの種類を指定する
    runs-on: macos-latest
    
    # job の中の工程を定義
    steps:
    
      # キャッシュからPodライブラリを取得する
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: Podfile.lock
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ hashFiles('**/Podfile.lock') }}
          
      # リポジトリを取得する
      - name: Checkout
        uses: actions/checkout@v3
        
      # Xcode 14を適用する
      - name: Force Xcode 14
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
        
      # CocoaPodsをインストールする
      - name: Install CocoaPods
        run: gem install cocoapods -v 1.11.2
        
      # インストールしたPodライブラリをキャッシュに保存する
      - name: Cache dependencies
        uses: actions/cache@v2
        
        # マーケットブレイスで提供されているパッケージを使用
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
           ${{ runner.os }}-pods-
      
      # .xcworkspace を作成
      - name: Install Dependencies
        run: |
         pod install
         if [ -d "Pods" ]; then
          cp -rf Pods ~/Library/Caches/CocoaPods/
         fi
      # テストを実行する
      - name: Run tests
        run: |
          xcodebuild test -workspace 1weekPDCA.xcworkspace -scheme 1weekPDCA -destination 'platform=iOS Simulator,name=iPhone 14'

```

</details>

**▼ 👍 追加でやりたいことメモ**
- `タイムアウトを設定する`
   Github Actions にも無料枠と有料枠がある。具体的には、Actions 利用時間が「2000分 / 月」までが無料枠だ。
   1 ワークフローにつき 360 分までのタイムアウトがデフォルトで設定されているが、意図せず水面下で長時間ワークフローが実行され、課金されるのは怖い。。。

**▼ 📚 参考文献**
- https://zenn.dev/yumemi_inc/articles/xctest-github-actions
- https://circleci.com/ja/blog/xcodebuild-exit-code-65-what-it-is-and-how-to-solve-for-ios-and-macos-builds/
- https://zenn.dev/koogawa/articles/54ff450a6dc5fd
- https://github.com/marketplace/actions/xcodebuild-action
- https://qiita.com/uhooi/items/29664ecf0254eb637951


心折れかけたけど、諦めなくてよかった。。
